--1
create TABLE app_user (
    ID          NUMBER GENERATED BY DEFAULT as IDENTITY, 
    userName    VARCHAR2(255),
    password    VARCHAR2(1024),
    IMAGE       VARCHAR2(1000) default 'https://i.pinimg.com/736x/da/5b/6e/da5b6e51745e0d72fdda9f3e869f281a.jpg',
    phone       char(11) check (regexp_like(phone, '[:digit:]{11}')),
    email       VARCHAR2(319),
    pic_id      NUMBER NOT NULL,
    job         VARCHAR2(50),
    location_id NUMBER NOT NULL,
    type        VARCHAR2(50),
    CONSTRAINT user_pk primary key (ID)

);

--2
create TABLE owner (
    house_id    NUMBER GENERATED BY DEFAULT as IDENTITY,
    IMAGE       VARCHAR2(1000) default 'https://media.gettyimages.com/photos/spacex-owner-and-tesla-ceo-elon-musk-arrives-on-the-red-carpet-for-picture-id1229892421?s=612x612',  
    CONSTRAINT owner_pk primary key (house_id) 


);

--3
create TABLE tenants(
    house_id        NUMBER GENERATED BY DEFAULT as IDENTITY, 
    family_members  NUMBER NOT NULL,
    IMAGE           VARCHAR2(1000) default 'https://ted-conferences-speaker-photos-production.s3.amazonaws.com/yoa4pm3vyerco6hqbhjxly3bf41d',
    CONSTRAINT tenants_owner_fk FOREIGN KEY (house_id) REFERENCES owner(house_id) 

);

--4
create TABLE apartment (
    apartment_id    NUMBER GENERATED BY DEFAULT as IDENTITY,     
    owner_id        NUMBER NOT NULL,        
    levels          NUMBER NOT NULL,
    lift            VARCHAR2(100),
    parking         VARCHAR2(100),

    CONSTRAINT apartment_pk primary key (apartment_id,owner_id)

);

--5
create TABLE flat ( 
    flat_id         NUMBER GENERATED BY DEFAULT as IDENTITY,          
    apartment_id    NUMBER NOT NULL,
    owner_id        NUMBER NOT NULL,
    floor_level     NUMBER NOT NULL,
    fee             NUMBER NOT NULL,
    no_of_bedrooms  NUMBER NOT NULL,
    no_of_bathrooms NUMBER NOT NULL,
    vacant          VARCHAR2(100),
    CONSTRAINT flat_pk primary key (flat_id),
    CONSTRAINT flat_apartment_fk FOREIGN KEY (apartment_id,owner_id) REFERENCES apartment(apartment_id,owner_id)

);

--6
create TABLE location (
    location_id     NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1), 
    street_address  VARCHAR2(1000),
    region          VARCHAR2(1000),
    thana           VARCHAR2(1000),
    district        VARCHAR2(1000),

    CONSTRAINT location_pk primary key (location_id)

);

--7
create TABLE deal(
    deal_id     NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),     
    owner_id    NUMBER NOT NULL,
    apartment_id NUMBER NOT NULL, 
    tenant_id   NUMBER NOT NULL UNIQUE, 
    flat_id     NUMBER NOT NULL UNIQUE,
    start_date  DATE,
    end_date    DATE,
    fee         NUMBER NOT NULL,

    CONSTRAINT deal_pk primary key (deal_id),
    CONSTRAINT deal_aparment_fk FOREIGN KEY (apartment_id,owner_id) REFERENCES apartment(apartment_id,owner_id),
    CONSTRAINT deal_flat_fk FOREIGN KEY(flat_id) REFERENCES flat(flat_id)  

);

--8
--according to sir's wish
create TABLE request(
    request_id  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1), 
    owner_id    NUMBER NOT NULL ,
    apartment_id NUMBER NOT NULL,
    house_id    NUMBER NOT NULL,
    tenant_id   NUMBER NOT NULL UNIQUE,  
    time        DATE NOT NULL,

    CONSTRAINT request_pk primary key (request_id),
    CONSTRAINT request_aparment_fk FOREIGN KEY (apartment_id,owner_id) REFERENCES apartment(apartment_id,owner_id),
    CONSTRAINT housepictures_owner_fk FOREIGN KEY (house_id) REFERENCES owner(house_id) 


);

--9
create TABLE housepictures(
    house_id    NUMBER NOT NULL,
    IMAGE       VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/97827-800x600.webp',
    exterior    VARCHAR2(1000) default 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    interior    VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1483157-800x600.webp',
    Rooftop     VARCHAR2(1000) default 'https://images.pexels.com/photos/103586/pexels-photo-103586.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    garage      VARCHAR2(1000) default 'https://images.pexels.com/photos/63294/autos-technology-vw-multi-storey-car-park-63294.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',

    CONSTRAINT housepictures_owner_fk FOREIGN KEY (house_id) REFERENCES owner(house_id) 



);

--10
create TABLE flatpictures(
    flat_id     NUMBER NOT NULL,
    IMAGE       VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472466-800x600.webp',
    bedroom     VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472465-800x600.webp',
    dining_room VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472467-800x600.webp',
    drawing_room VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472466-800x600.webp',
    kitchen     VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472470-800x600.webp',
    bathroom    VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472473-800x600.webp',
    store_room  VARCHAR2(1000) default 'https://images-cdn.bproperty.com/thumbnails/1472469-800x600.webp',

    CONSTRAINT flatpictures_flat_fk FOREIGN KEY(flat_id) REFERENCES flat(flat_id)

);

--11
create TABLE review(
    --review_id   NUMBER NOT NULL,
    rating      NUMBER NOT NULL,   
    comments     VARCHAR2(1024), 
    post_time    DATE NOT NULL,
    update_time  DATE NOT NULL,
    type        VARCHAR2(50)
    --CONSTRAINT review_pk primary_key (review_id)
);

--12
create TABLE tenant_review(
    owner_id    NUMBER NOT NULL,
    apartment_id NUMBER NOT NULL,
    tenant_id   NUMBER NOT NULL UNIQUE,
    description VARCHAR2(1000),

    CONSTRAINT tenant_review_aparment_fk FOREIGN KEY (apartment_id,owner_id) REFERENCES apartment(apartment_id,owner_id)



);

--13
create TABLE house_review(
    tenant_id   NUMBER NOT NULL,
    flat_id     NUMBER NOT NULL,
    description VARCHAR2(10000),

    CONSTRAINT house_review_flat_fk FOREIGN KEY(flat_id) REFERENCES flat (flat_id) 


);


-- --to add new column use alter
-- alter table table_name
--         add column_name datatype

-- -- Alter a Relational table to add a column

-- ALTER TABLE TABLE1 ADD
-- (
--   Column4 VARCHAR2(40)
-- );

-- --to delete a column use drop 

-- alter table table_name
--         drop column column_name


--App User data
-----------------------------
INSERT INTO app_user (ID, username, password, IMAGE, phone, email, pic_id, job, location_id, type) VALUES (1, 'Jonas', '123','https://i.pinimg.com/736x/da/5b/6e/da5b6e51745e0d72fdda9f3e869f281a.jpg', '01715760336', 'sakib@gmail.com', 201, 'Teacher', 1217, 'Rich');


--Owner Data
-----------------------------
INSERT INTO owner(house_id, IMAGE) VALUES (570,'https://media.gettyimages.com/photos/spacex-owner-and-tesla-ceo-elon-musk-arrives-on-the-red-carpet-for-picture-id1229892421?s=612x612 ');


--Tenant data
-----------------------------
INSERT INTO tenants(house_id, family_members, IMAGE) VALUES (495, 5, 'https://ted-conferences-speaker-photos-production.s3.amazonaws.com/yoa4pm3vyerco6hqbhjxly3bf41d');

--Apartment Data
-----------------------------
INSERT INTO apartment (apartment_id, owner_id, levels, lift, parking) VALUES (455, 420, 8, 'YES', 'YES');

--Flat Data
-----------------------------
INSERT INTO flat (flat_id, apartment_id, owner_id, floor_level, fee, no_of_bedrooms, no_of_bathrooms, vacant) VALUES (320, 330, 430, 5, 20000, 2, 2, 'YES');

--Location Data
------------------------------
INSERT INTO location (location_id, street_address, region, thana, district) VALUES(1218, '491/D North Palashi', 'হোমনা' , 'কুমিল্লা সদর',  'কুমিল্লা');

--HousePictures
------------------------------

INSERT INTO housepictures(house_id, IMAGE, exterior, interior, Rooftop, garage) VALUES('https://images-cdn.bproperty.com/thumbnails/97827-800x600.webp
',  'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'https://images-cdn.bproperty.com/thumbnails/1483157-800x600.webp ', 'https://images.pexels.com/photos/103586/pexels-photo-103586.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
 ',  'https://images.pexels.com/photos/63294/autos-technology-vw-multi-storey-car-park-63294.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
 ');

 --flatpictures
 ---------------------------

 INSERT INTO flatpictures(flat_id, IMAGE, bedroom, dining_room, drawing_room, kitchen, bathroom, store_room) VALUES (450, 'https://images-cdn.bproperty.com/thumbnails/1472466-800x600.webp', 'https://images-cdn.bproperty.com/thumbnails/1472465-800x600.webp', 'https://images-cdn.bproperty.com/thumbnails/1472467-800x600.webp', 'https://images-cdn.bproperty.com/thumbnails/1472466-800x600.webp', 'https://images-cdn.bproperty.com/thumbnails/1472470-800x600.webp',  'https://images-cdn.bproperty.com/thumbnails/1472473-800x600.webp',   'https://images-cdn.bproperty.com/thumbnails/1472469-800x600.webp');


 select * from app_user;
 select * from owner;
 select * from tenants;
 select * from apartment;
 select * from flat;
 select * from location;
 select * from housepictures;
 select * from flatpictures;
 select * from teant_review;

